all:
 vars:
   ansible_user: centos
   ansible_ssh_private_key_file: /home/anais/cpe/devops/tp3/key/id_rsa
   POSTGRES_USR: "usr"
   POSTGRES_DB: "db"
   POSTGRES_PASSWORD: "pwd"
   POSTGRES_URL: "database:5432"
 children:
   prod:
     hosts: centos@anais.delcamp.takima.cloud
